### ISSUE TITLE
Need help :(

### ISSUE THREAD

**Issue by kaneyxx** [monologg/BIO-R-BERT#2]
[My code here](https://github.com/kaneyxx/bio-r-bert/blob/master/bio-r-bert.ipynb)
I followed your scripts and modified to implement in jupyter. Just ran 1 epoch and found the weird result :(
Loss value increased and the prediction is all 0. If you have any free time, could you please help me to check this out?
Here's one another question, I read the R-BERT original paper and the author claims NO-SEP results might be better. In my code, I used Bio-BERT's tokenizer from transformers. It converts and add [SEP] automatically. Is it harmful to training?

**Comment by monologg** [comment]
First of all, you should change `bio_model = AutoModelWithLMHead.from_pretrained("monologg/biobert_v1.1_pubmed")` to `bio_model = AutoModel.from_pretrained("monologg/biobert_v1.1_pubmed")`

**Comment by monologg** [comment]
> Here's one another question, I read the R-BERT original paper and the author claims NO-SEP results might be better. In my code, I used Bio-BERT's tokenizer from transformers. It converts and add [SEP] automatically. Is it harmful to training?

It is just my personal opinion, but adding [SEP] doesn't make big difference because the model will automatically trained to ignore the information of [SEP] token.

**Comment by kaneyxx** [comment]
Got it, I will  modify the codes and run again. Big thanks for your help! 
BERT is so fun :D
