### ISSUE TITLE
It works!!! 

### ISSUE THREAD

**Issue by kaneyxx** [monologg/BIO-R-BERT#3]
Thanks for your comments! You are so professional!
[It works!](https://github.com/kaneyxx/bio-r-bert/blob/master/bio-r-bert.ipynb)
I built model by your config and from BertModel
result: micro F1 = 0.7968
I'm SO happy now :D 

Do you have any advise or comment for me to do further tasks or to try anything more about NLP?

**Comment by kaneyxx** [comment]
Another question, accuracy in result is around 50%. Is it the same as your experiment result?

**Comment by monologg** [comment]
> Thanks for your comments! You are so professional!
> [It works!](https://github.com/kaneyxx/bio-r-bert/blob/master/bio-r-bert.ipynb)
> I built model by your config and from BertModel
> result: micro F1 = 0.7968
> I'm SO happy now :D
> 
> Do you have any advise or comment for me to do further tasks or to try anything more about NLP?

I recommend you to try NER task on Bio. It would be best to see this [code](https://github.com/huggingface/transformers/blob/master/examples/ner/run_ner.py) thoroughly.

**Comment by monologg** [comment]
> Another question, accuracy in result is around 50%. Is it the same as your experiment result?

As I remember, accuracy wasn't low. You may need to check your code or try additional training and get a better result.
